# Generated by Django 5.2.15 on 2026-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Estimated token count for this message'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, help_text='Tool call metadata (which tools were invoked)', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the session is archived'),
        ),
    ]
